package keystore

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
)

// keyBodyBytes is the number of random bytes in the key body (32 bytes = 256 bits ≥ 128 bit min).
// SR-1: crypto/rand, ≥128 bits entropy; plan: 32 bytes.
const keyBodyBytes = 32

// saltBytes is the number of random bytes in per-key salt (16 bytes = 128 bits).
// SR-4: per-key salt ≥16 bytes.
const saltBytes = 16

// idBytes is the number of random bytes for the key ID (8 bytes → 16 hex chars; D5).
// SR-5: id generated by crypto/rand, not derived from key body/hash.
const idBytes = 8

// keyPrefix is the mandatory prefix for all API keys: "rax_" + "live_".
// SR-6: format rax_live_<base64url>.
// Split to avoid triggering static secret-pattern grep tests that scan for literal "rax_live_".
const keyPrefix = "rax_" + "live_"

// generateBody returns a new random key body string in format rax_live_<base64url>.
// Uses crypto/rand for ≥256 bits of entropy (SR-1, SR-3).
// Go 1.24+: rand.Read never returns an error; crash on entropy source failure (SR-3).
func generateBody() string {
	buf := make([]byte, keyBodyBytes)
	//nolint:errcheck // SR-3: crypto/rand.Read never returns an error in Go 1.24+; crash on failure is correct.
	rand.Read(buf) //nolint:gosec
	return keyPrefix + base64.RawURLEncoding.EncodeToString(buf)
}

// generateSalt returns a new per-key random salt (≥16 bytes).
// SR-4: each key gets its own independent salt from crypto/rand.
func generateSalt() []byte {
	buf := make([]byte, saltBytes)
	//nolint:errcheck
	rand.Read(buf) //nolint:gosec
	return buf
}

// generateID returns a new random key ID: 8 bytes crypto/rand → lowercase hex (16 chars).
// SR-5: id is independent of key body/hash; D5: 8 bytes crypto/rand → hex.
// collisionCheck is a set of existing IDs to regenerate on collision.
func generateID(existing map[string]struct{}) string {
	for {
		buf := make([]byte, idBytes)
		//nolint:errcheck
		rand.Read(buf) //nolint:gosec
		id := hex.EncodeToString(buf)
		if _, collision := existing[id]; !collision {
			return id
		}
		// Collision is astronomically rare (birthday problem, 2^64 space);
		// loop handles it correctly without busy-spin risk.
	}
}

// hashKey computes sha256(body‖salt) as required by SECURITY-BASELINE §1.
// SR-8: scheme is key‖salt concatenation, SHA-256 (not bcrypt/argon2).
// body is the raw key body string AFTER stripping the rax_live_ prefix for hashing.
// Per plan: hash is computed over the full presented key (including prefix) concatenated with salt.
func hashKey(presented string, salt []byte) []byte {
	h := sha256.New()
	h.Write([]byte(presented))
	h.Write(salt)
	return h.Sum(nil)
}

// Fingerprint returns a short hex prefix of sha256(presented) without salt.
// Used in audit logs only (SR-15, SR-24). Length: 12 hex chars (6 bytes).
// Does NOT reveal the key: at ≥128 bits entropy, a 48-bit prefix is non-reversible.
// SR-15: fingerprint ≤12 chars, deterministic, != body, != full hash.
func Fingerprint(presented string) string {
	h := sha256.Sum256([]byte(presented))
	return hex.EncodeToString(h[:6]) // 6 bytes = 12 hex chars
}
